version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-server-800
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Srikar@1829
      - MYSQL_DATABASE=notes
      - MYSQL_USER=srikar
      - MYSQL_PASSWORD=Srikar@1829
    ports:
      - "8082:3306"

  website:
    container_name: php722
    image: srikaradapa/php_img
    build:
      context: ./
    network_mode: host
    ports:
      - 8080:8080
    expose:
      - '8080'
    depends_on:
      - mysql
volumes:
  notes: {}


